#!/bin/sh

if [ -z "`which jq`" ]; then
    if [ -z "`which brew`" ]; then
        echo "Don't know how to install 'jq' (https://stedolan.github.io/jq/)."
        exit 1
    fi

    brew install jq || exit 1
fi

if [ -z "$1" ]; then
    echo "Usage: `basename $0` <linkname>"
    exit 1
fi

jq ".Functions[] | select(.LinkName==\"$1\") | .FullName" Library/BurstCache/JIT/CacheManifest.json

