#!/bin/sh

if [ $# -eq 0 ]; then
	echo "Usage: `basename $0` <logfile>"
	exit 1
elif [ ! -e "$1" ]; then
	echo "No such file: $1"
	exit 1
fi

case "`file -b --mime \"$1\" | sed -E 's/([^;]+).*/\1/'`" in
text/plain)
	cat "$1" | perl -i -p -e 's/\r+/\n/g' ;;
application/x-gzip)
	gzcat -d -S .xcactivitylog "$1" | perl -i -p -e 's/\r+/\n/g' ;;
*)
	echo "Unknown file type: $1"
	exit 1 ;;
esac

