#!/bin/sh

# http://developer.android.com/tools/help/adb.html

# an example .heydroid_config - drop one of these into your
# working directory (e.g. project build dir) to automatically
# use the right arguments when doing repetitive exercises:
#
# HEYDROID_SDK=/usr/local/android
# HEYDROID_APK=my.apk
# HEYDROID_PKG=com.pkg.my
# HEYDROID_APP=com.pkg.my.activity

if [ -e .heydroid_config ]; then
	. .heydroid_config
fi

if [ ! -d "$HEYDROID_SDK" ]; then
	echo "Unknown SDK directory, set HEYDROID_SDK"
	exit 1
fi

ADB=${HEYDROID_SDK}/platform-tools/adb

case "$1" in
h|help)
	echo "Usage: `basename $0` [command]"
	echo "Commands:"
	echo "  help"
	echo "  interactive                              (Default)"
	echo "  install [path/to/my.apk]"
	echo "  uninstall [com.pkg.my]"
	echo "  reinstall [path/to/my.apk] [com.pkg.my]"
	echo "  list"
	echo "  start [com.pkg.my[/com.pkg.my.activity]]"
	echo "  restart [com.pkg.my[/com.pkg.my.activity]]"
	echo "  kill [com.pkg.my]"
	echo "  profile [com.pkg.my]                     (Unity3D only)"
	echo "  log                                      (Unity3D only)"
	echo "  screencap <path/to/file.png>"
	echo "  screenrec <path/to/file.mp4> [length]"
	;;

i|install)
	apk="$2"
	if [ -z "$apk" ]; then apk="$HEYDROID_APK"; fi
	if [ -z "$apk" ]; then echo "`basename $0` $1 <path/to/my.apk>" && exit 1; fi
	${ADB} install $apk || exit 1 ;;

u|uninstall)
	pkg="$2"
	if [ -z "$pkg" ]; then pkg="$HEYDROID_PKG"; fi
	if [ -z "$pkg" ]; then echo "`basename $0` $1 <com.pkg.my>" && exit 1; fi
	${ADB} shell pm uninstall $pkg || exit 1 ;;

r|reinstall)
	$0 u $3 && $0 i $2 ;;

l|list)
	${ADB} shell pm list packages -f || exit 1 ;;

s|start)
	app="$2"
	if [ -z "$app" ]; then app="$HEYDROID_PKG/$HEYDROID_APP"; fi
    if [[ ! "$app" =~ / ]] || [[ "$app" =~ (^/)|(/$) ]]; then
        app=`adb shell dumpsys package | grep -Eio -m1 "$app/.+Unity.+Activity\$"`
    fi
    if [[ ! "$app" =~ / ]] || [[ "$app" =~ (^/)|(/$) ]]; then
        app=`adb shell dumpsys package | grep -Eio -m1 "$app/.+Activity\$"`
    fi
	if [ -z "$app" ]; then echo "`basename $0` $1 [com.pkg.my[/com.pkg.my.activity]]" && exit 1; fi
	${ADB} shell am start -n $app || exit 1 ;;

t|restart)
    $0 k $2 && $0 s $2 || exit 1 ;;

k|kill)
	pkg="$2"
	if [ -z "$pkg" ]; then pkg="$HEYDROID_PKG"; fi
	if [ -z "$pkg" ]; then echo "`basename $0` $1 <com.pkg.my>" && exit 1; fi
	${ADB} shell am force-stop $pkg || exit 1 ;;

p|profile)
	pkg="$2"
	if [ -z "$pkg" ]; then pkg="$HEYDROID_PKG"; fi
	if [ -z "$pkg" ]; then echo "`basename $0` $1 <com.pkg.my>" && exit 1; fi
	${ADB} forward tcp:34999 localabstract:Unity-$pkg || exit 1
	${ADB} forward --list || exit 1 ;;

o|log)
	${ADB} logcat -s Unity:IWEF | grep -Ev '^\w/\w+\s+\(\s*\d+\):\s*$' || exit 1 ;;

c|screencap)
	if [ -z "$2" ]; then echo "`basename $0` $1 <path/to/file.png>" && exit 1; fi
	if [ -n "$MSYSTEM" ]; then
		${ADB} shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > $2
	else
		${ADB} shell screencap -p > $2
	fi ;;

e|screenrec|screenrecord)
	tmp=/sdcard/screenrecord_$RANDOM.mp4
	len=10
	if [ -z "$2" ]; then echo "`basename $0` $1 <path/to/file.mp4>" && exit 1; fi
	if [ "$3" -eq "$3" ] 2>/dev/null; then len=$3; fi
	${ADB} shell screenrecord --time-limit $len "$tmp" && ${ADB} pull "$tmp" "$2 || exit 1"
	${ADB} shell rm -f "$tmp" ;;

''|interactive)
	if [ -e .heydroid_config ]; then
		echo $'Configuration: \e[96m' $HEYDROID_APK $'\e[0m:\e[92m' $HEYDROID_PKG $'\e[0m/\e[92m' $HEYDROID_APP $'\e[0m';
	fi
	${ADB} start-server || exit 1
	${ADB} devices
	while /bin/echo -n $'\e[96mhey\e[92mdroid\e[0m> ' && read -r line; do
		if [ -z "$line" ]; then line=$prev; fi
		if [ -n "$line" ]; then sh -c "$0 $line"; fi
		prev=$line
	done ;;

*)
	${ADB} $* ;;
esac

