#!/bin/sh

# http://developer.android.com/tools/help/adb.html

# an example .heydroid_config - drop one of these into your
# working directory (e.g. project build dir) to automatically
# use the right arguments when doing repetitive exercises:
#
# HEYDROID_SDK=/usr/local/android
# HEYDROID_APK=my.apk
# HEYDROID_PKG=com.pkg.my
# HEYDROID_APP=com.pkg.my.activity

if [ -e .heydroid_config ]; then
	. .heydroid_config
fi

if [ ! -d "$HEYDROID_SDK" ]; then
	echo "Unknown SDK directory, set HEYDROID_SDK"
	exit 1
fi

ADB=${HEYDROID_SDK}/platform-tools/adb

case "$1" in
h|help)
	echo "Usage: `basename $0` [command]"
	echo "Commands:"
	echo "  help"
	echo "  interactive                              (Default)"
	echo "  install [path/to/my.apk]"
	echo "  uninstall [com.pkg.my]"
	echo "  reinstall [path/to/my.apk] [com.pkg.my]"
	echo "  list"
	echo "  start [com.pkg.my/com.pkg.my.activity]"
	echo "  kill [com.pkg.my]"
	echo "  profile [com.pkg.my]                     (Unity3D only)"
	echo "  log                                      (Unity3D only)"
	echo "  screencap <path/to/file.png>"
	;;

i|install)
	apk="$2"
	if [ -z "$apk" ]; then apk="$HEYDROID_APK"; fi
	if [ -z "$apk" ]; then echo "`basename $0` $1 <path/to/my.apk>" && exit 1; fi
	${ADB} install $apk ;;

u|uninstall)
	pkg="$2"
	if [ -z "$pkg" ]; then pkg="$HEYDROID_PKG"; fi
	if [ -z "$pkg" ]; then echo "`basename $0` $1 <com.pkg.my>" && exit 1; fi
	${ADB} shell pm uninstall $pkg ;;

r|reinstall)
	$0 u $3 && $0 i $2 ;;

l|list)
	${ADB} shell pm list packages -f ;;

s|start)
	app="$2"
	if [ -z "$app" ]; then app="$HEYDROID_PKG/$HEYDROID_APP"; fi
	if [ -z "$app" ]; then echo "`basename $0` $1 <com.pkg.my/com.pkg.my.activity>" && exit 1; fi
	${ADB} shell am start -n $app ;;

k|kill)
	pkg="$2"
	if [ -z "$pkg" ]; then pkg="$HEYDROID_PKG"; fi
	if [ -z "$pkg" ]; then echo "`basename $0` $1 <com.pkg.my>" && exit 1; fi
	${ADB} shell am force-stop $pkg ;;

p|profile)
	pkg="$2"
	if [ -z "$pkg" ]; then pkg="$HEYDROID_PKG"; fi
	if [ -z "$pkg" ]; then echo "`basename $0` $1 <com.pkg.my>" && exit 1; fi
	${ADB} forward tcp:54999 localabstract:Unity-$pkg
	${ADB} forward --list ;;

o|log)
	${ADB} logcat -s Unity:IWEF | grep -Ev '^\w/\w+\s+\(\s*\d+\):\s*$' ;;

c|screencap)
	if [ -z "$2" ]; then echo "`basename $0` $1 <path/to/file.png>" && exit 1; fi
	${ADB} shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > $2 ;;

''|interactive)
	if [ -e .heydroid_config ]; then
		echo $'Configuration: \e[96m' $HEYDROID_APK $'\e[0m:\e[92m' $HEYDROID_PKG $'\e[0m/\e[92m' $HEYDROID_APP $'\e[0m';
	fi
	${ADB} start-server
	${ADB} devices
	while /bin/echo -n $'\e[96mhey\e[92mdroid\e[0m> ' && read -r line; do
		if [ -z "$line" ]; then line=$prev; fi
		if [ -n "$line" ]; then sh -c "$0 $line"; fi
		prev=$line
	done ;;

*)
	${ADB} $* ;;
esac

