#!/usr/bin/perl

use File::Basename;
use Getopt::Long;

GetOptions(
	'y' => \$dryrun, 'v+' => \$verbose, 'r=s' => \$rcs, 'a' => \$addonly,
	'f' => \$force, 'x=s' => \@excludes, 'm=s' => \@matches);

die("$0 [-f] [-y] [-a] [-r {p4|svn|git}] [-x <exclude> ...] [-m <match> ...] <source> <target>")
	if (scalar(@ARGV) != 2);

$source = $ARGV[0];
$target = $ARGV[1];
%dirs = ('.' => '');
$nadd = 0;
$ndel = 0;
$ncopy = 0;

$cmd = 'diff -r '.($verbose < 3 ? '-q' : '-u').
	" -x'.*'".join('', (map {" -x'$_'"} @excludes)).
	" '$source' '$target'";
print "$cmd\n" if ($verbose);

foreach $x (split(/\n/, `$cmd`)) {
	print "$x\n" if ($verbose > 1);
	next if ($verbose > 2);

	if ($x =~ s/^Files (.+) and .*$/\1/) {
		$op = 'copy';
	} elsif ($x =~ s/^Only in (.+): /\1\//) {
		$op = (index($x, $source) == 0) ? 'add' : 'del';
	}

	foreach $y ((-d "$x") ? split(/\n/, `find "$x" -type f`) : ($x)) {
		if (index($y, $source) == 0) {
			$s = $y;
			$t = ($target ne '.' ? "$target/" : '').substr($y, length($source) + 1);
		} else {
			$s = ($target ne '.' ? "$target/" : '').substr($y, length($source) + 1);
			$t = $y;
		}

		if ($op eq 'del') {
			if ($addonly || (scalar(@matches) > 0 && !(any {$t =~ /$_/ix} @matches))) {
				print "Ignoring $t\n" if ($verbose > 1);
			} elsif ($rcs eq 'p4') {
				$tt = $t =~ s/\%/25/gr =~ s/\@/%40/gr =~ s/\#/%23/gr =~ s/\*/%2A/gr =~ y/ /*/r;
				if (-f $y) {
					push(@cmds, ("p4 delete -c default '$tt'"));
					$ndel++;
				}
			} elsif ($rcs eq 'svn') {
				if (-f $y) {
					push(@cmds, ("svn remove '$t'"));
					$ndel++;
				}
			} elsif ($rcs eq 'git') {
				if (-f $y) {
					push(@cmds, ("git remove '$t'"));
					$ndel++;
				}
			} else {
				if (-f $y) {
					push(@cmds, ("rm -f '$t'"));
					$ndel++;
				}
			}
		} elsif ($op eq 'add') {
			$d = dirname($t);
			unless (exists $dirs{$d}) {
				$dirs{$d} = '';
				push(@cmds, "mkdir -p '$d'") if (! -d $d);
			}

			if ($rcs eq 'p4') {
				if (-f $y) {
					push(@cmds, ("cp '$s' '$t'", "p4 add -d -f -c default '$t'"));
					$nadd++;
				}
			} elsif ($rcs eq 'svn') {
				if (-f $y) {
					push(@cmds, ("cp '$s' '$t'", "svn add '$t'"));
					$nadd++;
				}
			} elsif ($rcs eq 'git') {
				if (-f $y) {
					push(@cmds, ("cp '$s' '$t'", "git add '$t'"));
					$nadd++;
				}
			} else {
				if (-f $y) {
					push(@cmds, ('cp'.($force ? ' -f' : '')." '$s' '$t'"));
					$nadd++;
				}
			}
		} elsif ($op eq 'copy') {
			if ($addonly || (scalar(@matches) > 0 && !(any {$t =~ /$_/ix} @matches))) {
				print "Warning! $t already exists\n" if ($addonly);
				print "Ignoring $t\n" if ($verbose > 1);
			} elsif ($rcs eq 'p4') {
				if (-f $y) {
					$tt = $t =~ s/\%/25/gr =~ s/\@/%40/gr =~ s/\#/%23/gr =~ s/\*/%2A/gr =~ y/ /*/r;
					push(@cmds, ("p4 edit -c default '$tt'", "cp '$s' '$t'"));
					$ncopy++;
				}
			} elsif ($rcs eq 'git') {
				if (-f $y) {
					push(@cmds, ("cp '$s' '$t'", "git add '$t'"));
					$ncopy++;
				}
			} else {
				if (-f $y) {
					push(@cmds, ('cp'.($force ? ' -f' : '')." '$s' '$t'"));
					$ncopy++;
				}
			}
		}
	}
}

foreach (@cmds) {
	print "$_\n" if ($verbose);
	system($_) unless ($dryrun);
}

print "Processed ".scalar(@cmds)." files: $nadd added $ndel deleted $ncopy copied\n";

