#!/usr/bin/perl

use File::Basename;
use Getopt::Long;
use List::MoreUtils qw(any);

GetOptions(
	'y' => \$dryrun, 'v+' => \$verbose, 'r=s' => \$rcs,
	'f' => \$force, 'x=s' => \@excludes, 'm=s' => \@matches);

die("$0 [-f] [-y] [-r {p4|git}] [-x <exclude> ...] [-m <match> ...] <source> <target>")
	if (scalar(@ARGV) != 2);

$source = $ARGV[0];
$target = $ARGV[1];
%dirs = ('.' => '');

$cmd = "diff -r ".($verbose < 2 ? '-q' : '-u').
	" -x\".*\"".join('', (map {" -x\"$_\""} @excludes)).
	" \"$source\" \"$target\"";
print "$cmd\n";

foreach $x (split(/\n/, `$cmd`)) {
	print "$x\n" if ($verbose);
	next if ($verbose > 1);

	if ($x =~ s/^Files (.+) and .*$/\1/) {
		$op = 'copy';
	} elsif ($x =~ s/^Only in (.+):/\1/) {
		$x =~ s/ ([^\s]+(\.[a-z]+)?)$/\/\1/;
		$op = (index($x, $source) == 0) ? 'add' : 'del';
	}

	foreach $y ((-d $x) ? split(/\n/, `find "$x" -type f`) : ($x)) {
		if (index($y, $source) == 0) {
			$s = $y;
			$t = ($target ne '.' ? "$target/" : '').substr($y, length($source) + 1);
		} else {
			$s = ($target ne '.' ? "$target/" : '').substr($y, length($source) + 1);
			$t = $y;
		}

		if ($op eq 'del') {
			if (scalar(@matches) > 0 && !(any {$t =~ /$_/ix} @matches)) {
				print "Filtered $t\n" if ($verbose);
			} elsif ($rcs eq 'p4') {
				$tt = $t =~ s/\%/25/gr =~ s/\@/%40/gr =~ s/\#/%23/gr =~ s/\*/%2A/gr =~ y/ /*/r;
				push(@cmds, ("p4 delete -c default \"$tt\"")) if (-f $y);
			} elsif ($rcs eq 'git') {
				push(@cmds, ("git remove \"$t\"")) if (-f $y);
			} else {
				push(@cmds, ("rm -f \"$t\"")) if (-f $y);
			}
		} elsif ($op eq 'add') {
			$d = dirname($t);
			unless (exists $dirs{$d}) {
				$dirs{$d} = '';
				push(@cmds, "mkdir -p \"$d\"") if (! -d $d);
			}

			if ($rcs eq 'p4') {
				push(@cmds, ("cp \"$s\" \"$t\"", "p4 add -d -f -c default \"$t\"")) if (-f $y);
			} elsif ($rcs eq 'git') {
				push(@cmds, ("cp \"$s\" \"$t\"", "git add \"$t\"")) if (-f $y);
			} else {
				push(@cmds, ("cp".($force ? ' -f' : '')." \"$s\" \"$t\"")) if (-f $y);
			}
		} elsif ($op eq 'copy') {
			if (scalar(@matches) > 0 && !(any {$t =~ /$_/ix} @matches)) {
				print "Filtered $t\n" if ($verbose);
			} elsif ($rcs eq 'p4') {
				$tt = $t =~ s/\%/25/gr =~ s/\@/%40/gr =~ s/\#/%23/gr =~ s/\*/%2A/gr =~ y/ /*/r;
				push(@cmds, ("p4 edit -c default \"$tt\"", "cp \"$s\" \"$t\"")) if (-f $y);
			} elsif ($rcs eq 'git') {
				push(@cmds, ("cp \"$s\" \"$t\"", "git add \"$t\"")) if (-f $y);
			} else {
				push(@cmds, ("cp".($force ? ' -f' : '')." \"$s\" \"$t\"")) if (-f $y);
			}
		}
	}
}

foreach (@cmds) {
	print "$_\n";
	system($_) unless ($dryrun);
}

