#!/bin/sh

a=`basename -s .sh $0`
d=.$a
l=$d/.list

case "$1" in
	help)
		echo "$a <command> [match]"
		echo ""
		echo "commands:"
		echo "	help         - show this help"
		echo "	update       - update stash list with modified files in the repository"
		echo "	status       - show current stash list"
		echo "	discard      - remove file from stash"
		echo "	obliterate   - remove entire stash"
		echo "	stow         - copy file into stash and revert in the repository"
		echo "	reset        - revert a stashed file in the repository"
		echo "	restore      - copy a stashed file back into the repository"
		echo "	diff         - show diff between stashed files and repository"
		echo "  changelist   - add or remove repository files from the stash list from a changelist"
		exit 1 ;;
	update)
		shift
		svn status $* | grep '^M' | sed -E 's/^M\s+//g' | tr '\\' '/' >> $l
		cat $l | sort | uniq | tee $l.tmp
		mv $l.tmp $l ;;
	status)
		if [ ! -e $l ]; then exit 1; fi
		shift
		while read p; do
			if [ $# -gt 0 ] && [ -z "`echo $p | grep \"$*\"`" ]; then continue; fi
			s=`echo $p | sha1sum | sed -E 's/\s.*+$//g'`
			if [ -e "$d/$s" ]; then
				if [ -z "`diff -q \"$p\" \"$d/$s\"`" ]; then echo "   $p"
				else echo "!  $p"; fi
			else echo "? $p"; fi
		done < $l ;;
	discard)
		if [ ! -e $l ]; then exit 1; fi
		shift
		if [ $# -gt 0 ]; then
			rm -f $l.tmp
			while read p; do
				if [ -z "`echo $p | grep \"$*\"`" ]; then echo $p | tee -a $l.tmp
				else echo "- $p"; fi
			done < $l
			mv $l.tmp $l
		fi ;;
	obliterate)
		rm -rf $d ;;
	stow)
		if [ ! -e $l ]; then exit 1; fi
		shift
		mkdir -p $d
		while read p; do
			if [ $# -gt 0 ] && [ -z "`echo $p | grep \"$*\"`" ]; then continue; fi
			s=`echo $p | sha1sum | sed -E 's/\s.*+$//g'`
			if [ -e "$p" ]; then cp -v "$p" "$d/$s" && svn revert "$p"; fi
		done < $l ;;
	reset)
		if [ ! -e $l ]; then exit 1; fi
		shift
		mkdir -p $d
		while read p; do
			if [ $# -gt 0 ] && [ -z "`echo $p | grep \"$*\"`" ]; then continue; fi
			if [ -e "$p" ]; then svn revert "$p"; fi
		done < $l ;;
	restore)
		if [ ! -e $l ]; then exit 1; fi
		shift
		while read p; do
			if [ $# -gt 0 ] && [ -z "`echo $p | grep \"$*\"`" ]; then continue; fi
			s=`echo $p | sha1sum | sed -E 's/\s.*+$//g'`
			if [ -e "$d/$s" ]; then cp -v "$d/$s" "$p"; fi
		done < $l ;;
	diff)
		if [ ! -e $l ]; then exit 1; fi
		shift
		while read p; do
			if [ $# -gt 0 ] && [ -z "`echo $p | grep \"$*\"`" ]; then continue; fi
			s=`echo $p | sha1sum | sed -E 's/\s.*+$//g'`
			if [ -e "$d/$s" ]; then diff -u "$p" "$d/$s"; fi
		done < $l ;;
	changelist)
		if [ ! -e $l ]; then exit 1; fi
		shift
		if [ $# -eq 0 ]; then echo "Wat?"; exit 1; fi
		z=$1
		shift
		while read p; do
			if [ $# -gt 0 ] && [ -z "`echo $p | grep \"$*\"`" ]; then continue; fi
			s=`echo $p | sha1sum | sed -E 's/\s.*+$//g'`
			if [ -e "$d/$s" ]; then svn cl $z "$p"; fi
		done < $l ;;
	*)
		echo "Huh?"
		exit 1 ;;
esac

